import fs from 'fs/promises'
import path from 'path'
import type { ControllerGroups, ExtendedRouteInfo, RouteParameter } from '../types/route.types'
import type { RPCGenerator, RPCGeneratorContext } from '../types/generator.types'
import type { GeneratedClientInfo, SchemaInfo } from '../types/schema.types'
import { camelCase, safeToString } from '../utils/string-utils'
import { groupRoutesByController } from './generator-utils'

/**
 * Built-in generator for TypeScript RPC clients.
 */
export class TypeScriptClientGenerator implements RPCGenerator {
	readonly name = 'typescript-client'

	constructor(private readonly outputDir: string) {}

	/**
	 * Generates the TypeScript RPC client.
	 */
	async generate(context: RPCGeneratorContext): Promise<GeneratedClientInfo> {
		return this.generateClient(context.routes, context.schemas)
	}

	/**
	 * Generates the TypeScript RPC client.
	 */
	async generateClient(
		routes: readonly ExtendedRouteInfo[],
		schemas: readonly SchemaInfo[]
	): Promise<GeneratedClientInfo> {
		await fs.mkdir(this.outputDir, { recursive: true })

		await this.generateClientFile(routes, schemas)

		const generatedInfo: GeneratedClientInfo = {
			generator: this.name,
			clientFile: path.join(this.outputDir, 'client.ts'),
			outputFiles: [path.join(this.outputDir, 'client.ts')],
			generatedAt: new Date().toISOString()
		}

		return generatedInfo
	}

	/**
	 * Generates the main client file with types included.
	 */
	private async generateClientFile(
		routes: readonly ExtendedRouteInfo[],
		schemas: readonly SchemaInfo[]
	): Promise<void> {
		const clientContent = this.generateClientContent(routes, schemas)
		const clientPath = path.join(this.outputDir, 'client.ts')
		await fs.writeFile(clientPath, clientContent, 'utf-8')
	}

	/**
	 * Generates the client TypeScript content with types included.
	 */
	private generateClientContent(routes: readonly ExtendedRouteInfo[], schemas: readonly SchemaInfo[]): string {
		const controllerGroups = groupRoutesByController(routes)

		return `// ============================================================================
// TYPES SECTION
// ============================================================================

/**
 * API Error class
 */
export class ApiError extends Error {
	constructor(
		public statusCode: number,
		message: string
	) {
		super(message)
		this.name = 'ApiError'
	}
}

/**
 * Clean separation of concerns for request options
 */
export type RequestOptions<
	TParams = undefined,
	TQuery = undefined,
	TBody = undefined,
	THeaders = undefined
> = (TParams extends undefined ? object : { params: TParams }) &
	(TQuery extends undefined ? object : { query: TQuery }) &
	(TBody extends undefined ? object : { body: TBody }) &
	(THeaders extends undefined ? object : { headers: THeaders })

/**
 * Custom fetch function type that matches the standard fetch API
 */
export type FetchFunction = (
	input: RequestInfo | URL,
	init?: RequestInit
) => Promise<Response>

// Generated DTOs and types from integrated Schema Generation
${this.generateSchemaTypes(schemas)}

// ============================================================================
// CLIENT SECTION
// ============================================================================

/**
 * Generated RPC Client
 * 
 * This class provides a type-safe HTTP client for interacting with your API endpoints.
 * It's automatically generated by the RPCPlugin based on your controller definitions.
 * 
 * @example
 * \`\`\`typescript
 * const apiClient = new ApiClient('http://localhost:3000')
 * 
 * // Make a request to get users
 * const response = await apiClient.users.getUsers()
 * 
 * // Make a request with parameters
 * const user = await apiClient.users.getUser({ params: { id: '123' } })
 * 
 * // Make a request with body data
 * const newUser = await apiClient.users.createUser({ 
 *   body: { name: 'John', email: 'john@example.com' } 
 * })
 * 
 * // Use with custom fetch function (e.g., for testing or custom logic)
 * const customFetch = (input: RequestInfo | URL, init?: RequestInit) => {
 *   console.log('Making request to:', input)
 *   return fetch(input, init)
 * }
 * 
 * const apiClientWithCustomFetch = new ApiClient('http://localhost:3000', {
 *   fetchFn: customFetch,
 *   defaultHeaders: { 'X-Custom-Header': 'value' }
 * })
 * \`\`\`
 * 
 * @generated This class is auto-generated by RPCPlugin
 */
export class ApiClient {
	private baseUrl: string
	private defaultHeaders: Record<string, string>
	private fetchFn: FetchFunction

	constructor(
		baseUrl: string, 
		options: {
			defaultHeaders?: Record<string, string>
			fetchFn?: FetchFunction
		} = {}
	) {
		this.baseUrl = baseUrl.replace(/\\/$/, '')
		this.defaultHeaders = {
			'Content-Type': 'application/json',
			...options.defaultHeaders
		}
		this.fetchFn = options.fetchFn || fetch
	}

	/**
	 * Set default headers for all requests
	 */
	setDefaultHeaders(headers: Record<string, string>): this {
		this.defaultHeaders = { ...this.defaultHeaders, ...headers }
		return this
	}


	/**
	 * Make an HTTP request with flexible options
	 */
	private async request<T>(
		method: string,
		path: string,
		options: RequestOptions<any, any, any, any> = {}
	): Promise<T> {
		const { params, query, body, headers = {} } = options as any
		
		// Build the final URL with path parameters
		let finalPath = path
		if (params) {
			Object.entries(params).forEach(([key, value]) => {
				finalPath = finalPath.replace(\`:\${key}\`, String(value))
			})
		}

		const url = new URL(finalPath, this.baseUrl)
		
		// Add query parameters
		if (query) {
			Object.entries(query).forEach(([key, value]) => {
				if (value !== undefined && value !== null) {
					url.searchParams.append(key, String(value))
				}
			})
		}

		// Merge default headers with request-specific headers
		const finalHeaders = { ...this.defaultHeaders, ...headers }

		const requestOptions: RequestInit = {
			method,
			headers: finalHeaders,
		}

		if (body && method !== 'GET') {
			requestOptions.body = JSON.stringify(body)
		}

		try {
			const response = await this.fetchFn(url.toString(), requestOptions)

			if (response.status === 204 || response.headers.get('content-length') === '0') {
				if (!response.ok) {
					throw new ApiError(response.status, 'Request failed')
				}
				return undefined as T
			}

			const contentType = response.headers.get('content-type') || ''
			const isJson = contentType.includes('application/json') || contentType.includes('+json')
			const responseData = isJson ? await response.json() : await response.text()

			if (!response.ok) {
				const message =
					typeof responseData === 'object' && responseData && 'message' in (responseData as Record<string, unknown>)
						? String((responseData as Record<string, unknown>).message)
						: typeof responseData === 'string' && responseData.trim()
							? responseData
							: 'Request failed'
				throw new ApiError(response.status, message)
			}

			return responseData as T
		} catch (error) {
			if (error instanceof ApiError) {
				throw error
			}
			throw new ApiError(0, error instanceof Error ? error.message : 'Network error')
		}
	}

${this.generateControllerMethods(controllerGroups)}
}
`
	}

	/**
	 * Generates controller methods for the client.
	 */
	private generateControllerMethods(controllerGroups: ControllerGroups): string {
		let methods = ''

		for (const [controllerName, routes] of controllerGroups) {
			const className = controllerName.replace(/Controller$/, '')
			methods += `
	// ${className} Controller
`
			methods += `	get ${camelCase(className)}() {
`
			methods += `		return {
`

			for (const route of routes) {
				const methodName = camelCase(safeToString(route.handler))
				const httpMethod = safeToString(route.method).toLowerCase()
				const { pathParams, queryParams, bodyParams } = this.analyzeRouteParameters(route)

				// Extract return type from route analysis for better type safety
				const returnType = this.extractReturnType(route.returns)

				const hasRequiredParams =
					pathParams.length > 0 ||
					queryParams.some((p) => p.required) ||
					(bodyParams.length > 0 && httpMethod !== 'get')

				// Generate the method signature with proper typing
				methods += `			${methodName}: async <Result = ${returnType}>(options${hasRequiredParams ? '' : '?'}: RequestOptions<`

				methods += `${this.generateParameterType(pathParams)}, `
				methods += `${this.generateParameterType(queryParams)}, `
				methods += `${this.generateParameterType(bodyParams)}, `

				// Headers type - always optional for now, but could be made conditional
				methods += 'undefined'

				methods += `>) => {
`

				methods += `				return this.request<Result>('${httpMethod.toUpperCase()}', \`${route.fullPath}\`, options)
`
				methods += `			},
`
			}

			methods += `		}
`
			methods += `	}
`
		}

		return methods
	}

	/**
	 * Extracts the proper return type from route analysis.
	 * Normalizes types that reference external symbols (e.g. Hono's TypedResponse)
	 * so the generated client is self-contained.
	 */
	private extractReturnType(returns?: string): string {
		if (!returns) return 'any'

		// Handle Promise<T> types
		const promiseMatch = returns.match(/Promise<(.+)>/)
		let type = promiseMatch ? promiseMatch[1] : returns

		// Strip TypedResponse<...> (Hono) so we don't reference undefined types in the client
		type = type.replace(/\s*&\s*TypedResponse<[^>]+>/g, '').trim()
		if (!type) return 'Response'

		return type
	}

	/**
	 * Generates schema types from integrated schema generation.
	 */
	private generateSchemaTypes(schemas: readonly SchemaInfo[]): string {
		if (schemas.length === 0) {
			return '// No schemas available from integrated Schema Generation\n'
		}

		let content = '// Schema types from integrated Schema Generation\n'
		for (const schemaInfo of schemas) {
			if (schemaInfo.typescriptType) {
				content += `${schemaInfo.typescriptType}\n\n`
			}
		}
		return content
	}

	/**
	 * Analyzes route parameters to determine their types and usage.
	 */
	private analyzeRouteParameters(route: ExtendedRouteInfo): {
		pathParams: readonly RouteParameter[]
		queryParams: readonly RouteParameter[]
		bodyParams: readonly RouteParameter[]
	} {
		const parameters = route.parameters || []

		const pathParams = parameters.filter((p) => p.decoratorType === 'param').map((p) => ({ ...p, required: true }))

		const bodyParams = parameters.filter((p) => p.decoratorType === 'body').map((p) => ({ ...p, required: true }))

		const queryParams = parameters
			.filter((p) => p.decoratorType === 'query')
			.map((p) => ({ ...p, required: p.required === true }))

		return { pathParams, queryParams, bodyParams }
	}

	/**
	 * Generate parameter typing with intersection support
	 */
	private generateParameterType(params: readonly RouteParameter[]): string {
		if (!params?.length) return 'undefined'

		const paramsNamed: string[] = []
		const paramsIntersection: string[] = []

		params.forEach((p) => {
			// data is missing from @Param() type intersection
			if (!p.data) {
				paramsIntersection.push(p.type)
			} else {
				const paramName = p.data
				const paramType = p.type || 'any'
				paramsNamed.push(`${paramName}: ${paramType}`)
			}
		})

		const parsedNamed = paramsNamed.length ? `{ ${paramsNamed.join(', ')} }` : undefined
		const parsedIntersection = paramsIntersection.length ? paramsIntersection.join(' & ') : undefined

		if (parsedNamed && parsedIntersection) return `${parsedIntersection} & ${parsedNamed}`

		return parsedNamed || parsedIntersection || 'undefined'
	}
}
